const express = require('express')
const router = express.Router()
const zingController = require('../controller/zingController')

router.get('/home', zingController.getHome)
router.get('/playlist', zingController.getPlayList)
router.get('/top-100', zingController.getTop100)
router.get('/song', zingController.getSong)
router.get('/search/all', zingController.getSearchAll)
router.get('/search/component', zingController.getSearchComponent)
router.get('/info-song', zingController.getInfoSong)
router.get('/zing-chart', zingController.getChart)
router.get('/new-release', zingController.getNewRelease)
router.get('/section-bottom', zingController.getSectionBottom)
module.exports = router